spring:
  application:
    name: project
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@nextit.or.kr:21521:xe
    username: TEAM202412_01
    password: oracle21c
  h2:
    enabled: false
  web:
    resources:
      static-locations: file:///C:/녹색제품 이미지
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.OracleDialect
  mail:
    host: smtp.naver.com
    port: 465
    username: lyg0095@naver.com
    password: G9VWZFBVQ2CY
    protocol: smtps
    properties:
     mail:
      smtp:
       auth: true
       ssl:
        enable: true
       starttls:
        enable: false
        required: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
  type:
    aliases-package: com.example.project
logging:
 level:
  root: info
 portone:
  imp_key: 1715881078062480
  imp_secret: JGft7elcfqCdsEHKjRNgmyQhF2et4HLKGZrUCf4xyTwt1g04wNcIwK6s4C8be1t69z5hqnWRtFTTCIY1

jwt:
  # The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HMAC-SHA algorithms MUST have a size >= 256 bits
  secret: 6364b0d2de554d3e942b1b8b048345251ce116d2a7264276973bb342f0e55def
  iss: nextit.or.kr
  sub: myapp-jwt
  # 1000 * 60(1분) * 60(1시간) * 24(시간) * 7 = 일주일
  expiration-milliseconds: 604800000
cookie:
  jwt:
   name: jwt_cookie
   http-only: false
   secure: false
   path: /
   maxAge: 604800 # maxAge는 초 단위
kakao:
  rest:
   api:
    key: 1364798dc5ed2d92b8449b3afc8c6f10
  redirect:
   uri: http://192.168.0.94:5173/login/auth
frontend:
  url: http://192.168.0.94:5173